version: "3"

services:
  web:
    container_name: example_web
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mongo    
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: example_mongo
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none